added --dont-close-pr

diff --git a/gh-combine-prs b/gh-combine-prs
--- a/gh-combine-prs
+++ b/gh-combine-prs
@@ -3,80 +3,86 @@
 set -euo pipefail
 
 help() {
-	cat << EOF
+    cat << EOF
 
 Usage: gh combine-prs --query "QUERY"
-	Combines multiple PRs into one.
+    Combines multiple PRs into one.
 
-	Required arguments:
-		--query "QUERY"
-				sets the query used to find combinable PRs.
-				e.g. --query "author:app/dependabot"
-				to combine Dependabot PRs
-	Optional arguments:
-		--selected-pr-numbers COMMA,SEPARATED,LIST
-				if set, will only work on PRs with the selected numbers.
-				e.g. --selected-pr-numbers 42,13,78
-				Defaults to selecting every PR matching the QUERY
-		--limit LIMIT
-				sets the maximum number of PRs that will be combined.
-				Defaults to 50
-		--skip-pr-check
-				if set, will combine matching PRs even if they are not passing checks.
-				Defaults to false when not specified
-		--combined-branch-name
-				if set, use this instead of combined-pr-branch branch name
-				
+    Required arguments:
+        --query "QUERY"
+                sets the query used to find combinable PRs.
+                e.g. --query "author:app/dependabot"
+                to combine Dependabot PRs
+    Optional arguments:
+        --selected-pr-numbers COMMA,SEPARATED,LIST
+                if set, will only work on PRs with the selected numbers.
+                e.g. --selected-pr-numbers 42,13,78
+                Defaults to selecting every PR matching the QUERY
+        --limit LIMIT
+                sets the maximum number of PRs that will be combined.
+                Defaults to 50
+        --skip-pr-check
+                if set, will combine matching PRs even if they are not passing checks.
+                Defaults to false when not specified
+        --combined-branch-name "NAME"
+                if set, use this instead of combined-pr-branch branch name
+        --dont-close-pr
+                if set, leave dependa bot pr opened 		
+                
 
 EOF
 }
 
 confirm() {
-	while read -r -n1 key; do
-		if [[ $key == $'\e' ]]; then
-			exit 0
-		else
-			break
-		fi
-	done
+    while read -r -n1 key; do
+        if [[ $key == $'\e' ]]; then
+            exit 0
+        else
+            break
+        fi
+    done
 }
 
 LIMIT=50
 QUERY=""
 SKIP_PR_CHECK="false"
+CLOSE_PR="true"
 SELECTED_PR_NUMBERS=
 COMBINED_BRANCH_NAME="combined-pr-branch"
 while [ $# -gt 0 ]; do
-	case "$1" in
-	-h|--help)
-		help
-		exit 0
-		;;
-	--selected-pr-numbers)
-		shift
-		SELECTED_PR_NUMBERS=$1
-		;;
-	--limit)
-		shift
-		LIMIT=$1
-		;;
-	--query)
-		shift
-		QUERY=$1
-		;;
-	--skip-pr-check)
-		SKIP_PR_CHECK="true"
-		;;
-	--combined-branch-name)
-		shift
-		COMBINED_BRANCH_NAME=$1	
-		;;
-	*)
-		help >&2
-		exit 1
-		;;
-	esac
-	shift
+    case "$1" in
+    -h|--help)
+        help
+        exit 0
+        ;;
+    --selected-pr-numbers)
+        shift
+        SELECTED_PR_NUMBERS=$1
+        ;;
+    --limit)
+        shift
+        LIMIT=$1
+        ;;
+    --query)
+        shift
+        QUERY=$1
+        ;;
+    --skip-pr-check)
+        SKIP_PR_CHECK="true"
+        ;;
+    --combined-branch-name)
+        shift
+        COMBINED_BRANCH_NAME=$1	
+        ;;
+    --dont-close-pr)
+        CLOSE_PR="false"
+        ;;	
+    *)
+        help >&2
+        exit 1
+        ;;
+    esac
+    shift
 done
 
 DEFAULT_BRANCH=$(gh api /repos/:owner/:repo --jq '.default_branch')
@@ -84,36 +90,36 @@ COMBINED_BRANCH=$COMBINED_BRANCH_NAME
 BODY_FILE=/tmp/.combined-pr-body.md
 
 if [[ -z "${QUERY}" ]]; then
-	help
-	echo "Error: --query is required; e.g. --query \"author:app/dependabot\""
-	exit 1
+    help
+    echo "Error: --query is required; e.g. --query \"author:app/dependabot\""
+    exit 1
 fi
 
 cat <<- EOF > $BODY_FILE
-	Combining multiple dependencies PRs into one.
+    Combining multiple dependencies PRs into one.
 
-	<details>
-	<summary>Instructions for merging</summary>
+    <details>
+    <summary>Instructions for merging</summary>
 
-	* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
-	* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick \`Allow merge commits\` in the repository settings.
-	* When ready, merge this PR using \`Create a merge commit\`.
+    * **Use a merge commit**, so that GitHub will mark all original PRs as merged.
+    * If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick \`Allow merge commits\` in the repository settings.
+    * When ready, merge this PR using \`Create a merge commit\`.
 
-	</details>
+    </details>
 
-	## Combined PRs
+    ## Combined PRs
 
 EOF
 
 echo "The following PRs will be evaluated for inclusion:"
 gh pr list --search "${QUERY}" --limit "${LIMIT}"
 if [[ "${SKIP_PR_CHECK}" == "true" ]]; then
-	echo -e "\nAction status checks for PRs will be skipped"
+    echo -e "\nAction status checks for PRs will be skipped"
 fi
 JQ_FILTER=".[]"
 if [[ -n "${SELECTED_PR_NUMBERS}" ]]; then
-	echo -e "\nOnly the following PRs will be selected: $SELECTED_PR_NUMBERS"
-	JQ_FILTER="$JQ_FILTER | select(.number == ($SELECTED_PR_NUMBERS))"
+    echo -e "\nOnly the following PRs will be selected: $SELECTED_PR_NUMBERS"
+    JQ_FILTER="$JQ_FILTER | select(.number == ($SELECTED_PR_NUMBERS))"
 fi
 echo "Press any key to continue or escape to abort"
 confirm
@@ -128,27 +134,32 @@ git checkout -b "$COMBINED_BRANCH"
 count=0
 gh pr list --search "${QUERY}" --limit "${LIMIT}" --json headRefName,number | jq -r "$JQ_FILTER | [.number,.headRefName] | @tsv" | while read -r NUMBER HEADREF
 do
-	if [[ "${SKIP_PR_CHECK}" == "false" ]] && [[ $(gh pr checks "$NUMBER" | cut -d$'\t' -f2 | grep -E "fail|pending" -c) -gt 0 ]]; then
-		echo "Not all checks are passing - skipping PR #$NUMBER"
-		continue
-	fi
+    if [[ "${SKIP_PR_CHECK}" == "false" ]] && [[ $(gh pr checks "$NUMBER" | cut -d$'\t' -f2 | grep -E "fail|pending" -c) -gt 0 ]]; then
+        echo "Not all checks are passing - skipping PR #$NUMBER"
+        continue
+    fi
 
-	echo "Trying to merge $HEADREF into $COMBINED_BRANCH"
-	if [[ ! $(git merge "origin/$HEADREF" --no-edit) ]]; then
-		echo "Unable to merge $HEADREF - skipping PR #$NUMBER"
-		git merge --abort
-		continue
-	fi
-	echo "Merged $HEADREF (#$NUMBER) into $COMBINED_BRANCH"
+    echo "Trying to merge $HEADREF into $COMBINED_BRANCH"
+    if [[ ! $(git merge "origin/$HEADREF" --no-edit) ]]; then
+        echo "Unable to merge $HEADREF - skipping PR #$NUMBER"
+        git merge --abort
+        continue
+    fi
+    echo "Merged $HEADREF (#$NUMBER) into $COMBINED_BRANCH"
 
-	DESCRIPTION=$(gh pr view "$NUMBER" --json title,author,number --template '{{.title}} (#{{.number}}) @{{.author.login}}')
-	echo "* ${DESCRIPTION}" >> $BODY_FILE
+    DESCRIPTION=$(gh pr view "$NUMBER" --json title,author,number --template '{{.title}} (#{{.number}}) @{{.author.login}}')
+    echo "* ${DESCRIPTION}" >> $BODY_FILE
 
-	((count=count+1))
-	if [[ $count == "$LIMIT" ]]; then
-		echo "Hit limit of $LIMIT - no more PRs will be added"
-		break
-	fi
+    ((count=count+1))
+    if [[ $count == "$LIMIT" ]]; then
+        echo "Hit limit of $LIMIT - no more PRs will be added"
+        break
+    fi
+    if [[ "${CLOSE_PR}" == "true" ]]; then
+        echo -e "\nClosing dependa-bot pr"
+        gh pr close "$NUMBER" -d
+    
+    fi
 done
 
 echo -e "Preview of PR:\n\n"
